### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by KhaldiDataPanda** [BIGmama-technology/Hiring-AI-engineer#18]
greetings, got few questions :
- i wanna know if you have a benchmark of the performance of the previous models so i can compare if i get better results.
- will you add more tasks soon ?

**Comment by 1hachem** [comment]
salam @KhaldiDataPanda, no benchmark is set for the moment, would you like to work on one ? if you would we can add this as a task.

**Comment by KhaldiDataPanda** [comment]
That would be great yes .

**Comment by 1hachem** [comment]
task added, btawfiq inchalah ! 📿
