### ISSUE TITLE
I cant push my branch 

### ISSUE THREAD

**Issue by eliasboulham** [BIGmama-technology/Hiring-AI-engineer#21]
$ git push origin EliasBoulham
ERROR: Permission to BIGmama-technology/Hiring-AI-engineer.git denied to eliasboulham.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by 1hachem** [comment]
Our main branch is protected, you have to fork this repo, push to your fork and once you finish open a pullrequest.

**Comment by 1hachem** [comment]
## Step 1: Fork the Repository

1. Go to the [BIGmama-technology/Hiring-AI-engineer](https://github.com/BIGmama-technology/Hiring-AI-engineer) repository on GitHub.
2. In the top-right corner of the page, click the "Fork" button.
3. This will create a copy of the repository in your own GitHub account. You'll be redirected to your fork once it's done.

## Step 2: Clone Your Fork

1. On your fork's GitHub page, click the "Clone or download" button and copy the URL.
2. Open a terminal on your machine.
3. Clone your fork using the command: `git clone <URL-you-copied>`
   - Replace `<URL-you-copied>` with the URL you copied from your fork.
4. Navigate into the cloned directory: `cd Hiring-AI-engineer`

## Step 3: Create a New Branch

1. Before making changes, create a new branch: `git checkout -b <your-branch-name>`
   - Replace `<your-branch-name>` with a name related to the changes you'll be making.

## Step 4: Make Your Changes and Commit Them

1. Make your changes to the files.
2. Add your changes to staging: `git add .`
3. Commit your changes: `git commit -m "A descriptive message about your changes"`

## Step 5: Push Changes to Your Fork

1. Push your changes: `git push origin <your-branch-name>`

## Step 6: Open a Pull Request

1. Go to your fork on GitHub.
2. Click the "Pull request" button next to your branch.
3. Adjust the pull request details as necessary, then submit it.

Your pull request will be reviewed by the maintainers of the original repository. They may request further changes or merge it into the main branch if everything looks good.

Thank you for contributing to the Hiring-AI-engineer project! Your efforts help us build a better product.

---

Remember to replace any placeholder URLs or names with the actual ones used by your project. This README should help guide contributors through the process smoothly and clarify the contribution workflow.

**Comment by eliasboulham** [comment]
‫في السبت، 17 فبراير 2024 في 8:29 م تمت كتابة ما يلي بواسطة ‪Hachem
Betrouni‬‏ ***@***.***‬‏>:‬
