### ISSUE TITLE
push problem

### ISSUE THREAD

**Issue by AmineMAALEM** [BIGmama-technology/Hiring-AI-engineer#8]
I apologize for the inconvenience but i am encountering issues while trying to push changes to the repository 
here what I did :
Cloned the repository locally.
Made changes to the code.
Attempted to push changes using the command git push origin my_branch_name.

error : fatal: unable to access 'https://github.com/BIGmama-technology/Hiring-AI-engineer.git/': The requested URL returned error: 403

I verified that my GitHub account has the necessary permissions.

i also tried ssh approach : 
Generated SSH key using ssh-keygen.
Added the key to the SSH agent with ssh-add.
Configured Git to use the SSH key.
Checked SSH key with ssh-add -l and verified it's added.

error: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by 1hachem** [comment]
Salam alikom Amin, I suppose that running `git remote -v` will print that your fetch and push origins are `https://github.com/BIGmama-technology/Hiring-AI-engineer.git/` which is OUR repo which you done have push access to, instead you need to update your remote origin run : 

```bash
git remote set-url origin git@github.com:AmineMAALEM/Hiring-AI-engineer.git
```
this way you push to your fork, from there you can create a pull request !
btawfiq,

**Comment by AmineMAALEM** [comment]
salam 3laykoum, thank you Hachem for your replay, but I still have the same problem 
![Capture1](https://github.com/BIGmama-technology/Hiring-AI-engineer/assets/125833566/99ef715e-5647-4180-a199-097c432378a2)
![image](https://github.com/BIGmama-technology/Hiring-AI-engineer/assets/125833566/58216792-5dee-4d96-b47f-8785a8a663a7)

**Comment by AmineMAALEM** [comment]
![image](https://github.com/BIGmama-technology/Hiring-AI-engineer/assets/125833566/a5dbabe5-b183-4285-8039-63a9e3781ced)

**Comment by 1hachem** [comment]
make sure you have your ssh keys set-up the right way https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
